verilog-blink/Makefile

Added DFU to Blink Makefile

---

litex/workshop_rgb.py

Applying same as [Add the DFU suffix inside the workshop.py script](https://github.com/im-tomu/fomu-workshop/commit/b5c15ef64227b5c90b33d86da63a3b85b48df0f8) to `workshop_rgb.py`.

Add .dfu file creation in workshop_rgb.py

---

verilog-blink-minimal/blink.v

this appears to fix issue #59 that I raised.

added defines to avoid missing compiler directive error

---

docs/requirements.rst

Signed-off-by: Sean Cross <sean@xobs.io>

requirements: update requirements to v2.0.3

---

docs/bootloader.rst
docs/index.rst
docs/requirements.rst

* Move the bootloader updating text into it's own file.
* Add example session to the bootloader updating.
* Fill out the requirements section a little more.
See changes at;
* https://mithro-fomu-workshop.readthedocs.io/en/master/requirements.html
* https://mithro-fomu-workshop.readthedocs.io/en/master/bootloader.html

Improving the updating section.

---

riscv-blink/src/main.c

Small C code formating fix

---

litex/workshop.py
litex/workshop_rgb.py

Hope is this fixes https://github.com/im-tomu/fomu-workshop/issues/97

Updating ValentyUSB.

---

docs/conf.py

- How to buy.
- How to report an issue.
- How to get help.
- Fomu Website.

Adding some more top links.

---

riscv-rust-blink/Cargo.lock
riscv-rust-blink/Cargo.toml
riscv-rust-blink/src/rgb.rs
riscv-rust-blink/src/timer.rs

Removes some casts and looks a bit nicer

Update to v0.0.3 of fomu-pac

---

.github/tests.sh
.github/travis-pretty.inc.sh
.travis.yml
get-toolchain.py

Fixes #107 
Adds a `get-toolchain.py` script which downloads the latest fomu toolchain and then runs the various steps that are in this repository.

Adding CI for various steps

---

riscv-zig-blink/README.md
riscv-zig-blink/build.zig
riscv-zig-blink/src/fomu.zig
riscv-zig-blink/src/main.zig

Main change is due to https://github.com/ziglang/zig/pull/4509

zig: update for current zig master version

---

README.md

Signed-off-by: Daniel Lim Wee Soong <weesoong.lim@gmail.com>

Fix link to sphinx_materialdesign_theme

---

.gitattributes
.github/tests.sh
.travis.yml
get-toolchain.py
riscv-zig-blink/README.md
riscv-zig-blink/build.zig
riscv-zig-blink/src/fomu.zig

I managed to crash my usb drivers somehow... until I reboot I won't be able to actually test this.
(though if someone else wants to give it a try and confirms it works, then we can merge)

Update to zig 0.6.0

---

docs/background.rst

Signed-off-by: Tim Callahan <tcal@google.com>

Don't mix assignment styles in the same Verilog block.

---

docs/conf.py
docs/python.rst

Issue #266 
Signed-off-by: Tim Callahan <tcal@google.com>

Fix link for riscv-blink csr.h.

---

chisel/blink/.gitignore
chisel/blink/Makefile
chisel/blink/build.sbt
chisel/blink/project/build.properties
chisel/blink/src/Blink.scala

[Chisel](https://github.com/chipsalliance/chisel3) is a hardware construction language embedded in Scala.
I tried to stay as close as possible to the Verilog blink example. Tested on rev PVT.

add chisel blink example

---

docs/icestudio.rst

Add a video (converted to an animated GIF) of the Fomu being programmed from Icestudio and the resulting rainbow patterm.
/cc @tcal-x

doc: add IceStudio Blinky video

---

verilog/blink/README.md

verilog/blink: it works on Windows

---

docs/mixed-hdl.rst

- fix environment variables quoting

docs/mixed-hdl: fix formatting

---

docs/environment.yml

Fixes #518
Refs:
- https://github.com/SymbiFlow/symbiflow-examples/issues/169
- https://github.com/SymbiFlow/symbiflow-examples/pull/171
- https://github.com/google/skywater-pdk/pull/333
- https://github.com/conda/conda/issues/10815

docs: fix conda env (pypa/pip#10237)

---

.github/tests.sh
hdl/ghdl-prefix.mk
hdl/mixed/blink/Makefile
hdl/vhdl/blink/Makefile

Fixes https://github.com/im-tomu/fomu-workshop/issues/583

Set GHDL_PREFIX for VHDL examples

---

.github/workflows/test.yml
riscv-zig-blink/README.md
riscv-zig-blink/build.zig
riscv-zig-blink/src/fomu.zig
riscv-zig-blink/src/fomu/rgb.zig

This is a fix for https://github.com/im-tomu/fomu-workshop/issues/609
I tried to lock CI on Mac OS to only install a specific version, but it doesn't seem to work.

Fix zig issues in CI

---

docs/environment.yml

Remove Python version restriction.
