riscv-blink/src/main.c

This also speeds up the speed of the rgb animation

Remove one of the duplicate i++ in the main-loop

---

riscv-blink/Makefile

The CROSS_COMPILE variable is widely used among free and open
source projects like Linux, u-boot, etc.
Signed-off-by: Denis 'GNUtoo' Carikli <GNUtoo@cyberdimension.org>

riscv-blink: Makefile: use CROSS_COMPILE instead of TRGT

---

riscv-usb-cdcacm/Makefile

The CROSS_COMPILE variable is widely used among free and open
source projects like Linux, u-boot, etc.
Signed-off-by: Denis 'GNUtoo' Carikli <GNUtoo@cyberdimension.org>

riscv-usb-cdcacm: Makefile: use CROSS_COMPILE instead of TRGT

---

riscv-blink/src/main.c

Remove the blink rate modification that's supposed to be added during the workshop. It looks like it got added by accident in #46

riscv-blink: Remove blink rate override

---

litex/lxbuildenv.py

`sys.exit` raises a `SystemExit` exception which causes a bare except to always trigger. IE the below always prints hello.
```python
import sys
try:
sys.exit(0)
except:
print("Hello")
```
However, SystemExit doesn't inherit from Exception, so the following works as expected.
```python
import sys
try:
sys.exit(0)
except Exception:
print("Hello")
```

Make lxbuildenv.py return 0 on success.

---

riscv-zig-blink/.gitignore
riscv-zig-blink/README.md
riscv-zig-blink/build.zig
riscv-zig-blink/ld/linker.ld
riscv-zig-blink/src/fomu.zig
riscv-zig-blink/src/fomu/messible.zig
riscv-zig-blink/src/fomu/reboot.zig
riscv-zig-blink/src/fomu/rgb.zig
riscv-zig-blink/src/fomu/start.zig
riscv-zig-blink/src/fomu/timer0.zig
riscv-zig-blink/src/fomu/touch.zig
riscv-zig-blink/src/main.zig

[zig](https://ziglang.org/) is a relatively new programming language that hopes to make you never reach for C again.
This PR has the basic blink demo working from zig.

Add zig example

---

docs/python.rst

Update the MicroPython firmware version output example to match the advice to
match the advice at start of tutorial to upgrade to version 2.0.3 firmware.
(Spotted as inconsistency while working through tutorial.)

docs: MicroPython example: 2.0.3 firmware

---

docs/riscv.rst

Update the RISCV wishbone-tool firmware version output example to match
the advice at the start of the tutorial to upgrade to version 2.0.3
firmware.
(Same as for the docs-python branch; I would have pushed it to the same pull request branch, but that one was already merged :-) )

docs: RISCV example: 2.0.3 firmware

---

docs/riscv.rst

The wishbone-tool gdb port changed to 3333 at least by 2020-01-17 in https://github.com/litex-hub/wishbone-utils/commit/18a911e3b0247522fbdac7de266e033e70428b68 and possibly earlier.  
Update example output/commands in the documentation to match the current wishbone-tool.

docs: Update wishbone-tool gdb port

---

README.md
docs/Makefile
docs/migen.rst
docs/verilog.rst
verilog/blink-basic/README.md

Minor tweaks to the main README (to better separate the commands from description of the commands) and to wishbone docs.
Also fix a couple of places where the blink example is using the old name.

Minor doc tweaks

---

.gitmodules
docs/migen.rst
migen/blink-expanded.py
migen/blink.py
migen/fomu.py
migen/lxbuildenv.py

This PR creates a "Migen-only" version of the verilog examples provided in #124.
The idea was to only depend on migen alone, thus I've replicated the board configurations partially (also to demonstrate, how boards would be configured in migen). It also makes use of the lxbuildenv-infrastructure in the same way as the litex-examples in order to provide the migen dependencies (with the same revision).
Finally, it removes the corresponding FIXME from docs by providing a description.

Add Migen example

---

docs/renode-zephyr.rst

Following all the instructions in order leaves you with python3.6 from
the TOMU toolchain first in your PATH, which doesn't work for building
zephyr.
Add a note to remove it from your PATH.   
Fixes #134

Note which python version to use building zephyr

---

docs/renode-bridge.rst
docs/riscv.rst
docs/verilog.rst

The Sphinx `session::` feature can take an optional language marker, which then allows it to parse the example included and generate a more context appropriate copy'n'paste action.  The language marker was missing in some `session::` examples, and there was one `code:: bash` usage left not using session.
For https://github.com/im-tomu/fomu-workshop/issues/144#issuecomment-595993657 change these over to language tagged `session::` examples.

Tag documentation sessions with language for better copy'n'paste

---

docs/renode-zephyr.rst

With regard to #179, we need to update the path to Zephyr binary in Renode.
It is not copy-paste ready, but now it's evident.
Unfortunately Renode does not have an option to reference $HOME.

Update path to Zephyr

---

docs/migen.rst

Add examples of changing color using wishbone-tool and fomu_rgb_output CSR:
```
$ wishbone-tool 0x60003000 0x1 # make LED green
$ wishbone-tool 0x60003000 0x2 # make LED red
$ wishbone-tool 0x60003000 0x3 # make LED yellow   
$ wishbone-tool 0x60003000 0x4 # make LED blue
$ wishbone-tool 0x60003000 0x5 # make LED teal
$ wishbone-tool 0x60003000 0x6 # make LED pink
$ wishbone-tool 0x60003000 0x7 # make LED white
```
NOTE: I have a different address for the CSR so I changed the tutorial to match:
```
pdp7@x1:~/dev/fpga/fomu-workshop/litex/build$ cat csr.csv 
#--------------------------------------------------------------------------------
#--------------------------------------------------------------------------------
csr_base,timer0,0x60002800,,
csr_base,fomu_rgb,0x60003000,, …
```

Add example of changing LED color with wishbone-tool

---

docs/Makefile
docs/conf.py
docs/translations/pot/background.pot
docs/translations/pot/bootloader.pot
docs/translations/pot/hdl.pot
docs/translations/pot/help.pot
docs/translations/pot/index.pot
docs/translations/pot/migen.pot
docs/translations/pot/python.pot
docs/translations/pot/renode-bridge.pot
docs/translations/pot/renode-starting.pot
docs/translations/pot/renode-verilator.pot
docs/translations/pot/renode-zephyr.pot
docs/translations/pot/renode.pot
docs/translations/pot/requirements.pot
docs/translations/pot/riscv.pot
docs/translations/pot/verilog.pot

This PR adds initial support for internationalisation of `fomu-workshop` website content, we however need to make decision about how we are going to structure it to move forward...
There is no support in for internationalisation URIs in Sphinx by default, so I suppose there is some other, to me hidden logic behind the URIs having `en` when [looking at the deployed version](https://workshop.fomu.im/en/latest/).
What is the deployment logic? Where is the site hosted? Wouldn't it be wise to move to GitHub Pages and GitHub Actions for CI/CD pipeline? We could then deploy each language version into a sub-directory (cs, en, de,...) and have a landing page at web-root...
We can also import these Gettext `pot` files into something like [Weblate](https://weblate.org/en/features/), @nijel offers …

Add i18n support

---

docs/translations/pot/verilog.pot
docs/verilog.rst

"blink" cycles through 8 colors.  "blink-expanded" responds to inputs.
DO I NEED TO MAKE PARALLEL CHANGES IN translations/pot/verilog.pot?
Is one generated from the other?
Update: I did make the analogous changes in verilog.pot.
Signed-off-by: Tim Callahan <tcal@google.com>

Fix references to "verilog/blink" vs "verilog/blink-expanded".

---

README.md
docs/conf.py
docs/requirements.txt

It seems that the package was renamed, but this repo was not updated accordingly. The repository is correctly forwarded, but `doc/conf.py` fails because `sphinxcontrib_verilog_diagrams` does not exist. It is named `sphinxcontrib_hdl_diagrams` now. This PR fixes the requirements file, the Sphinx config file and the README.
Note that several of dependabot's PRs are failing because of this issue.

sphinxcontrib-verilog-diagrams was renamed to sphinxcontrib-hdl-diagrams

---

README.md
docs/conf.py
docs/requirements.txt

Close #314
This PR is build on top of #314.
On the one hand, spacing of the lists in the README is fixed.
On the other hand, a step for installing dependencies (`requirements.txt`) is added to the instructions for building the docs locally.
**EDIT**
CI failure seems to be related to #212.

readme: fix list spacing, add requirements step to local build

---

.github/workflows/test.yml

The usage of `add-path` in the Ubuntu job of the contributed GitHub Actions workflow produces a warning annotation: https://github.com/im-tomu/fomu-workshop/actions/runs/289836222.
That is because GitHub deprecated the feature: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/. Writing to an environment variable is recommended instead: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#adding-a-system-path.

ci: use GITHUB_ENV instead of add-path

---

.github/workflows/test.yml

In GitHub Actions a token is available by default (`${{ github.token }}`, see https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#github-context). At the same time, `get-toolchain.py` expects an envvar named `GH_TOKEN`. In this PR, the envvar is set, so that authentication is used. This will hopefully reduce rate limit issues.

ci: rate limit

---

.github/workflows/doc.yml

Fixes #142
A GitHub Actions workflow named 'doc' is added for building the docs.
- The output is uploaded as an artifact of the workflow run, as well as pushed to branch `gh-pages`.
- Users can download the artifact of any run for having an offline version of the docs (#142).
- Any contributor that forks the repo (and pushes changes) will have the content automatically uploaded to `username.github.io/fomu-workshop`.

GitHub Actions: test and doc

---

.github/workflows/doc.yml

As discussed in https://github.com/im-tomu/fomu-workshop/pull/317#issuecomment-704425058, this PR ensures that `gh-pages` will be updated from branch `master` only.
All other branches and/or PR will trigger the CI workflow, the site will be built and it will be available as an artifact (zipfile). However, `gh-pages` and [im-tomu.github.io/fomu-workshop](https://im-tomu.github.io/fomu-workshop/) will only be updated once changes are merged into `master`.
/cc @mithro

ci: update gh-pages from branch 'master' only

---

DEVELOPMENT.md
README.md

This PR is an aesthetical update to the README:
- Shields/badges are added.
- Images of the board are added.
- Development sections are moved to `DEVELOPMENT.md`.
See result at https://github.com/umarcor/fomu-workshop/tree/readme/shields

readme: add shields/badges, move 'Development' sections to a separated file

---

.github/tests.sh

This PR allows preserving envvar `TOOLCHAIN_PATH`, in case the user set it to some other value before running the tests.

test: preserve TOOLCHAIN_PATH, if set

---

.github/tests.sh

Currently, Migen tests are not executed in CI. This PR adds them to `tests.sh`.

ci: add Migen examples to tests.sh

---

board.mk
mixed-hdl/blink/Makefile
verilog/blink-expanded/Makefile
verilog/blink/Makefile
vhdl/blink/Makefile

As discussed in https://github.com/im-tomu/fomu-workshop/pull/334#discussion_r501902116, this PR restores the dependency of `bling.json` on the PCF file.

board.mk: split PCF from PNRFLAGS

---

.github/tests.sh
.github/workflows/test.yml

This solves one half of issue https://github.com/im-tomu/fomu-workshop/issues/383

ci: add Chisel Blink, use Action setup-scala

---

docs/icestudio.rst

An apio version supporting Fomu was released to PyPI. Therefore, updating it manually from git is not required anymore.

doc/icestudio: no need to get apio from git anymore

---

.gitattributes

Seen in https://github.com/antonblanchard/microwatt/issues/225

gitattributes: add linguist-language attributes for Verilog and VHDL sources

---

.github/hdl-tests.sh
.github/tests.sh
.github/workflows/test.yml
hdl/mixed/blink/Makefile
hdl/vhdl/blink/Makefile

In this PR, the tests corresponding to the examples in subdir 'hdl' are moved to a separated script (`hdl-tests.sh`). Then, a CI job is added for showcasing how to execute those inside a single container containing all the required tools (GHDL, Yosys, ghdl-yosys-plugin and nextpnr). Other jobs do still execute all the tests, since `hdl-tests.sh` is called from `tests.sh`.
In fomu-toolchain, ghdl-yosys-plugin is statically built into Yosys. However, in containers, it is built as a module. That's why envvar GHDL_PLUGIN_MODULE is added to the vhdl and mixed makefiles.

ci: run hdl tests on all-in-one container

---

.github/workflows/test.yml
docs/mixed-hdl.rst
docs/requirements/software.rst
docs/verilog.rst
docs/vhdl.rst
hdl/container.mk
hdl/mixed/blink/Makefile
hdl/verilog/blink-expanded/Makefile
hdl/verilog/blink/Makefile
hdl/vhdl/blink/Makefile

This is the last in the recent series of PRs. Support for fine-grained usage of containers is added.
- In the existing all-in-one CI job, a single container is used, and make is executed inside.
- In the new fine-grained CI job, make is executed on the host and one container is used for each of the tools.
Replacing "local" tools with containers is done through `container.mk`, allowing users to easily decide which tools to run locally or which specific container images to use.
By the way, variables DESIGN and TOP are used in the Makefiles, for making them more generic.

ci: run hdl tests on fine-grained containers 

---

.github/hdl-tests.sh
.github/tests.sh
.github/workflows/test.yml
README.md
hdl/PnR_Prog.mk
hdl/mixed/blink/Makefile
hdl/verilog/blink-expanded/Makefile
hdl/verilog/blink/Makefile
hdl/vhdl/blink/Makefile

This PR includes several non critical updates:
- `hdl/PnR_Prog.mk` is added, for reducing duplication in the Makefiles used for Verilog and/or VHDL examples.
- MSYS2 jobs are added to CI, for testing that examples can be used by installing tools through `pacman`, instead of using fomu-toolchain.
- The README is updated. Some references were wrong, and other were missing.
- Litex example `workflow_rgb` was not tested in CI. I added it.

add hdl/PnR_Prog.mk, add MSYS2 CI, update README, test litex/workflow_rgb.py

---

docs/hdl.rst

All these currently point to 404s on the current workshop docs. Updated to point into hdl/ , except for migen which is top level

Update repo reference

---

.github/tests.sh

Execution of example RISC-V Zig on macOS has been failing in CI for two months now: https://github.com/im-tomu/fomu-workshop/runs/2798889344?check_suite_focus=true#step:10:5219.
That is preventing CI in fomu-toolchain from finishing successfully and, thus, publishing new releases. Therefore, I'm disabling that example on that platform until someone familiar with it can have a better look. My perception is it might be due to an update of zig from 0.6.0 to 0.8.0.
/cc @daurnimator as per https://github.com/im-tomu/fomu-workshop/commits/master/riscv-zig-blink

ci: skip RISC-V Zig Example test on macOS

---

.github/tests.sh
docs/migen.rst

The path seems to be dependent of the board revision now, updated it to use `$FOMU_REV` appropriately.

docs/migen: fix binary path

---

hdl/mixed/blink/Makefile
hdl/verilog/blink-expanded/Makefile
hdl/verilog/blink/Makefile
hdl/vhdl/blink/Makefile

- set default shell to bash
- add pipefail option
Fixes #412

hdl: remove yosys-report.txt

---

docs/riscv.rst

The output path for the `cdc_msc` firmware doesn't seems to be target dependent anymore.
Note: I didn't manage to get the tinyusb demo working, see https://github.com/hathach/tinyusb/issues/179#issuecomment-888923621

docs/risc-v: fix tinyusb firmware path

---

DEVELOPMENT.md
docs/conf.py
docs/requirements.txt

Building the docs in CI is failing because symbolator cannot be installed properly. However, it seems that it is not being used. This PR removes the dependency.

docs: remove unused dependency 'symbolator'

---

docs/python.rst

Addresses #75.
Modeled on the udev section on adding a user to the `plugdev` group.
https://workshop.fomu.im/en/latest/requirements/drivers.html#steps-to-set-up-udev-rule

doc: Add comment on /dev/ttyACM permissions and dialout group

---

get-toolchain.py

The platform lookup table is not used if the 'CI' env variable is not set, breaking the toolchain download.

get_toolchain: Fix platform detection

---

hdl/mixed/blink/Makefile

Recent version of yosys changed default behavior when reading verilog file. Seem we must use read_verilog command. So the command
```
$(DESIGN).json: $(VHDL_SYN_FILES) $(VERILOG_SYN_FILES)
$(QUIET) $(YOSYS) $(YOSYSFLAGS) \
-p \
"$(GHDLSYNTH) $(GHDL_FLAGS) $(VHDL_SYN_FILES) -e; \
synth_ice40 \
-top $(TOP) \
-json $@" $(VERILOG_SYN_FILES) 2>&1 | tee yosys-report.txt
``` 
must be changed to 
```
$(DESIGN).json: $(VHDL_SYN_FILES) $(VERILOG_SYN_FILES)
$(QUIET) $(YOSYS) $(YOSYSFLAGS) \
-p \
"$(GHDLSYNTH) $(GHDL_FLAGS) $(VHDL_SYN_FILES) -e; \
read_verilog $(VERILOG_SYN_FILES); \
synth_ice40 \
-top $(TOP) \
-json $@" 2>&1 | tee yosys-report.txt
```

Recent version of yosys need read_verilog command

---

.readthedocs.yml

Fixes https://github.com/im-tomu/fomu-workshop/issues/825.

Add the `build` definition to `.readthedocs.yml`.
